(defun tkb-fix-whitespace ()
  (interactive)
  (goto-char (point-min))
  (while (re-search-forward "^[ \t]+" nil t)
    (replace-match "" nil nil)))

(defun tkb-fix-para ()
  (interactive)
  (while (search-forward "<para>" nil t)
    (when (eolp) (delete-char 1))
    (when (search-forward "</para>" nil t)
      (goto-char (match-beginning 0))
      (when (bolp) (delete-char -1)))))
