(defun tkb-set-font ()
  (interactive)
  (let* ((W (x-display-pixel-width))
	 (H (x-display-pixel-height))
	 (WxH (format "%dx%d" W H))
	 (font (case W
		 ((1280)
		  "-*-dejavu sans mono-medium-r-normal--12-0-0-0-m-0-iso10646-1")
		 ((1600)
		  "-*-dejavu sans mono-medium-r-normal--15-0-0-0-m-0-iso10646-1")
		 ((1920 1900 1856)
		  "-*-dejavu sans mono-medium-r-normal--17-0-0-0-m-0-iso10646-1")))
	 (parameter-alist `(font .  ,font)))
    (set-frame-font font)
    (push parameter-alist default-frame-alist)
    (push parameter-alist initial-frame-alist)))
