;;; Testing debugging of when-exec-found

(defun x ()
  (interactive)
  (when-exec-found "ls"
    (print "first alt")
    (list 'ls))
  (when-exec-found (exename "ls")
    (print "second alt")
    exename)
  (when-exec-found (exename '("bogus" "ls"))
    (print "third alt")
    (list 'after-bogus exename))
  (when-exec-found (exename '("bogus" "ls")
			    '("/sbin" "/bin" "/usr/sbin" "/usr/bin"))
    (print "fourth alt")
    (list 'path-specified exename))
  (let ((ename "bogus"))
    (when-exec-found (exename ename)
      (print "second alt as variable")
      exename))
  (let ((ename "ls"))
    (when-exec-found (exename ename)
      (print "second alt as variable, found")
      exename))
  (let ((ename "ls")
	(path-list '("/sbin" "/bin" "/usr/sbin" "/usr/bin")))
    (when-exec-found (exename ename path-list)
      (print "third alt as variable, found")
      exename)))
