(require 'cl)


(defun genadv (what n)
  (interactive "cGenerate (S)cience fiction or (F)antasy? \nnHow many? ")
  (cond
   ((or (eq what ?s) (eq what ?S))
    (genadv-output genadv-science-fiction-table n))
   ((or (eq what ?f) (eq what ?F))
    (genadv-output genadv-fantasy-table n))
   (t
    (message "Can't figure out what you want."))))


(defun genadv-output (table count)
  (let ((buf (get-buffer-create "*genadv*")))
    (with-current-buffer buf
      (erase-buffer)
      (switch-to-buffer buf)

      (cl-loop for i from 1 to count
               do (genadv-idea table))
      (goto-char (point-min))
      (set-buffer-modified-p nil))))


(defun genadv-left-justify (s n)
  (concat s (make-string (- n (length s)) ? )))


(defun genadv-idea (table)
  (let* ((labels '(("DO"            . do)
                   ("SOMETHING"     . something)
                   ("LOCATION"      . location)
                   ("COMPLICATIONS" . complications)
                   ("OPPOSITION"    . opposition)))
         (width (1+ (cl-loop for i in labels maximize (length (car i))))))
    
    ;; TODO: (cl-loop for (key . value) in '((a . 1) (b . 2)) collect value)

    (cl-loop for i in labels
             do
             (insert (genadv-left-justify (car i) width))
             (insert (genadv-item (symbol-value (cdr (assoc (cdr i) table)))))
             (insert "\n"))
    (insert "\n")))


;; TODO: (cl-loop for x = (random) when (> x 0) return x)
;; (cl-loop for x in my-list  with res = nil  do (push x res) finally return res)

(defun genadv-item (options)
  (let ((count 1)
        (rtn))
    (while (> count 0)
      (let ((item (aref options (random (length options)))))
        (if (eq item 'roll-twice)
            (setq count (1+ count))
          (push item rtn)
          (setq count (1- count)))))
    (mapconcat 'identity rtn ", ")))




(defconst genadv-science-fiction-do
  [
   "Aid"
   "Assassinate"
   "Assault"
   "Assist"
   "Attack"
   "Avenge"
   "Battle"
   "Beset"
   "Blow up"
   "Chase"
   "Combat"
   "Conceal"
   "Contend with"
   "Create"
   "Defeat"
   "Defend"
   "Deliver"
   "Destroy"
   "Discover"
   "Disguise"
   "Encounter"
   "Escape From"
   "Escort"
   "Fight"
   "Fight"
   "Find"
   "Foil"
   "Get Past"
   "Guard"
   "Guide"
   "Invade"
   "Investigate"
   "Join"
   "Kill"
   "Liberate"
   "Locate"
   "Meet"
   "Move"
   "Negotiate With"
   "Obliterate"
   "Observe"
   "Oppose"
   "Protect"
   "Protect"
   "Race"
   "Repel"
   "Rescue"
   "Resist"
   "Retrieve"
   "Reveal"
   "Safeguard"
   "Save"
   "Serve"
   "Shield"
   "Steal"
   "Strike"
   "Support"
   "Take"
   "Track"
   "Trade With"
   "Trap"
   "Travel with"
   "Understand"
   "Watch"
   ])


(defconst genadv-science-fiction-something
  [
   "Agent"
   "Alien"
   "Ally"
   "Ancients"
   "Android"
   "Artifact"
   "Bounty Hunter"
   "Broker"
   "Businessman"
   "Captain"
   "Child"
   "Computer"
   "Corporation"
   "Creature"
   "Criminial"
   "Diplomat"
   "Disaster"
   "Discovery"
   "Enemy"
   "Energy"
   "Fleet"
   "Friend"
   "Godlike Aliens"
   "Government"
   "Information"
   "Item"
   "Love Interest"
   "Man"
   "Mercenary"
   "Merchant"
   "Murderer"
   "New Race"
   "Organization"
   "Outcast"
   "Outworlder"
   "Pilot"
   "Planet"
   "Police"
   "Politician"
   "Priest"
   "Primitives"
   "Princess"
   "Rebel"
   "Rebels"
   "Rival"
   "Robot"
   "Rogue"
   "Scientist"
   "Secret"
   "Smuggler"
   "Soldiers"
   "Spatial Anomaly"
   "Starship"
   "Stranger"
   "Technician"
   "Technology"
   "Terrorist"
   "The Unexplained"
   "Treasure"
   "Villian"
   "Warlike Alien"
   "Warrior"
   "Weapon"
   "Woman"
   ])


(defconst genadv-science-fiction-location 
  [
   "\"Bermuda Triangle\""
   "Alien World"
   "Asteroid Field"
   "Bar"
   "Barren World"
   "Black Hole"
   "Border"
   "Casino"
   "City"
   "Colony"
   "Core World"
   "Corporate Headquarters"
   "Deep Space"
   "Desert Planet"
   "Fortress"
   "Frontier"
   "Gas Giant"
   "Government Installation"
   "Governmental Center"
   "Hideout"
   "Homeworld"
   "Ice Planet"
   "In Orbit"
   "In Transit"
   "Jungle Planet"
   "Lawless Zone"
   "Military Base"
   "Moon"
   "Mountain Planet"
   "Neutral Space"
   "New World"
   "Orbital Installation"
   "Other Dimension"
   "Outlands"
   "Planet"
   "Planetoid"
   "Pleasure Planet"
   "Primitive World"
   "Prison"
   "Quarantined Zone"
   "Research Facility"
   "Ruins"
   "Secret Location"
   "Skyplex"
   "Solar System"
   "Space Habitat"
   "Space Lanes"
   "Space Station"
   "Spaceport"
   "Spatial Anomaly"
   "Starship"
   "Temple"
   "The Sun"
   "Trade Zone"
   "Transit Point"
   "Under Water"
   "Underground"
   "Villian's Base"
   "Void"
   "Vortex"
   "War Zone"
   "Wasteland"
   "Water Planet"
   roll-twice
   ])


(defconst genadv-science-fiction-complications
  [
   "Abduction"
   "Alien Psychology"
   "Ambush"
   "Attention"
   "Barriers"
   "Battle"
   "Betrayal"
   "Bureaucracy"
   "Computer Failure"
   "Contract"
   "Corporate Influence"
   "Crash"
   "Criminals"
   "Desperation"
   "Differing PC motivations"
   "Diplomacy"
   "Disaster"
   "Disease"
   "Distractions"
   "Double-Cross"
   "Drugs"
   "Enemies"
   "Enemy"
   "Equipment Failure"
   "Exploration"
   "Fear"
   "Godlike Alien"
   "Government influence"
   "Insanity"
   "Interested Parties"
   "Interference"
   "Invasion"
   "Lack of trust"
   "Language"
   "Legal Trouble"
   "Love Interest"
   "Military Influence"
   "Misdirection"
   "Mistaken Identity"
   "Money"
   "Monster"
   "Mystery"
   "None"
   "Politics"
   "Power Struggle"
   "Recuring NPC"
   "Red Herring"
   "Rivalry"
   "Robot"
   "Scientific Problem"
   "Security"
   "Side-tracked"
   "Spatial Anomaly"
   "Squabbling"
   "The Unexplained"
   "Theft"
   "Transport problem"
   "Trap"
   "Travel"
   "Travel Problems"
   "Trickery"
   "Unexplained"
   "Vendetta"
   "War"
   ])


(defconst genadv-science-fiction-opposition 
  [
   "Agency"
   "Aliens"
   "Android"
   "Assassin"
   "Bounty Hunter"
   "Clones"
   "Company"
   "Computer"
   "Conspiracy"
   "Creature"
   "Criminals"
   "Empire"
   "Enemy"
   "Enemy"
   "Explorer"
   "Fanatic"
   "Former Ally"
   "Friend"
   "Gang"
   "Government official"
   "Hazardous Environment"
   "Invader"
   "Law Enforcement"
   "Lunatic"
   "Mecenary"
   "Merchant"
   "Military"
   "Monster"
   "Mutant"
   "Mysterious Aliens"
   "Navigational Trouble"
   "None"
   "Organization"
   "Outlaw"
   "Outworlder"
   "Paradox"
   "Pilot"
   "Police"
   "Puzzle"
   "Rebel"
   "Recurring NPC"
   "Religious Figure"
   "Robot"
   "Ruler"
   "Scientist"
   "Shadowy Figure"
   "Ship Captain"
   "Specialist"
   "Spy"
   "Starship"
   "Stranger"
   "Superior Aliens"
   "Technological Breakdown"
   "Technology gone Amok"
   "Terrorists"
   "Thief"
   "Time"
   "Traitor"
   "Unidentified Vessel"
   "Veteran"
   "Villain"
   "War"
   "Warlike Aliens"
   roll-twice
   ])


(defconst genadv-fantasy-something
  [
   "Abberation"
   "Ally"
   "Angel"
   "Animal"
   "Army"
   "Artifact"
   "Barbarian"
   "Bard"
   "Castle"
   "Child"
   "Construct"
   "Creature"
   "Demon"
   "Dragon"
   "Dungeon"
   "Enemy"
   "Friend"
   "Gem or Jewel"
   "Giant"
   "God"
   "Government"
   "Guards"
   "Humanoid"
   "Humanoid"
   "Item"
   "Kingdom"
   "Love Interest"
   "Magic"
   "Magic Item"
   "Magical Beast"
   "Magical Event"
   "Man"
   "Map"
   "Merchant"
   "Monk"
   "Monster"
   "Monster"
   "New Race"
   "Noble"
   "Oracle"
   "Organization"
   "Outsider"
   "Peasants"
   "Priest"
   "Princess"
   "Prophecy"
   "Rival"
   "Rogue"
   "Ruler"
   "Secret"
   "Secret"
   "Soldiers"
   "Sorcerer"
   "Stranger"
   "Teasure"
   "Thief"
   "Undead"
   "Village"
   "Villain"
   "Warlord"
   "Warrior"
   "Weapon"
   "Wizard"
   "Woman"
   ])


(defconst genadv-fantasy-location
  [
   "Across the sea"
   "Another Plane"
   "Battlefield"
   "Bazaar"
   "Border"
   "Castle"
   "Catacombs"
   "Cave"
   "Cavern"
   "Citadel"
   "City"
   "City"
   "Desert"
   "Distant Kingdom"
   "Dungeon"
   "Dungeon"
   "Dungeon"
   "Evil Land"
   "Fane"
   "Foreign Land"
   "Forest"
   "Fortress"
   "Frontier"
   "Guild Hall"
   "Hamlet"
   "Hills"
   "Jungle"
   "Keep"
   "Lost City"
   "Manor"
   "Monster's Lair"
   "Mountain"
   "Nearby Kingdom"
   "Ocean"
   "Outlands"
   "Palace"
   "Plains"
   "Port"
   "Road"
   "Ruins"
   "Secret Location"
   "Sepulcher"
   "Ship"
   "Sky"
   "Stronghold"
   "Subterranean City"
   "Swamp"
   "Tavern"
   "Temple"
   "The East"
   "The North"
   "The South"
   "The West"
   "Tomb"
   "Town"
   "Trade Route"
   "Underground"
   "Underworld"
   "Vault"
   "Village"
   "Villian's Lair"
   "Wasteland"
   "Wizard's Tower"
   "Woods"
   ])

(defconst genadv-fantasy-complications
  [
   "Abduction"
   "Ambush"
   "Attention"
   "Barriers"
   "Battle"
   "Betrayal"
   "Bureaucracy"
   "Construct"
   "Criminals"
   "Desparation"
   "Differing PC motivations"
   "Diplomancy"
   "Disaster"
   "Distractions"
   "Double-Cross"
   "Drugs"
   "Enemies"
   "Enemy"
   "Equipment Failure"
   "Exploration"
   "Fear"
   "Getting Lost"
   "God(s)"
   "Guild Influence"
   "Insanity"
   "Interested Parties"
   "Interference"
   "Invasion"
   "Lack of trust"
   "Language"
   "Legal Trouble"
   "Love Interest"
   "Magic"
   "Magical Event"
   "Military influence"
   "Misdirection"
   "Mistaken Identity"
   "Money"
   "Monsters"
   "Monsters"
   "Mystery"
   "None"
   "Politics"
   "Power Struggle"
   "Puzzles"
   "Race"
   "Recurring NPC"
   "Red Herring"
   "Religion"
   "Riddles"
   "Rivalry"
   "Royal influence"
   "Side-tracked"
   "Spies"
   "Squabbling"
   "Superstition"
   "Theft"
   "Trap"
   "Travel"
   "Travel problem"
   "Trickery"
   "Vendetta"
   "War"
   "Weather"
   ])

(defconst genadv-fantasy-opposition
  [
   "Abberation"
   "Adventurer"
   "Artifact"
   "Assassin"
   "Barbarian"
   "Champion"
   "Conspiracy"
   "Construct"
   "Creature"
   "Criminals"
   "Cult"
   "Demon/Devil"
   "Dragon"
   "Dragon"
   "Enemy"
   "Enemy"
   "Enemy"
   "Fanatic"
   "Former Ally"
   "Friend"
   "Gang"
   "Giants"
   "Gods"
   "Government official"
   "Guild"
   "Hazardous Environment"
   "Humanoid"
   "Humanoid"
   "Humanoid"
   "Immortal"
   "Invader"
   "Lunatic"
   "Magic-User"
   "Magical Beast"
   "Mastermind"
   "Mercenary"
   "Merchant"
   "Military"
   "Monster"
   "Monster"
   "Nation"
   "None"
   "Outlaw"
   "Outsider"
   "Priest"
   "Puzzle"
   "Recurring NPC"
   "Ruler"
   "Shadowy Figure"
   "Sorcerer"
   "Spy"
   "Stranger"
   "Thief"
   "Time"
   "Traiter"
   "Undead"
   "Veteran"
   "Villian"
   "War"
   "Warlord"
   "Warrior"
   "Watchmen"
   "Wizard"
   roll-twice
   ])


(defconst genadv-science-fiction-table
  '((do . genadv-science-fiction-do)
    (something . genadv-science-fiction-something)
    (location . genadv-science-fiction-location )
    (complications . genadv-science-fiction-complications)
    (opposition . genadv-science-fiction-opposition)))
    

(defconst genadv-fantasy-table
  '((do . genadv-science-fiction-do)
    (something . genadv-fantasy-something)
    (location . genadv-fantasy-location)
    (complications . genadv-fantasy-complications)
    (opposition . genadv-fantasy-opposition)))


